# Azure Pipeline for the Tridion Salesforce Addon #

# environment + other reusable variables
variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'

  disable.coverage.autogenerate: 'true'
  buildConfiguration: 'Release'

# pipeline trigger
trigger: none

jobs:
  - job: "BuildAddon_Job"
    displayName: Build Addon

    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 5.0 SDK'
        inputs:
          packageType: 'sdk'
          version: '5.0.x'

      - task: DotNetCoreCLI@2
        displayName: 'Restore Packages'
        inputs:
          command: 'restore'
          projects: |
            **/SalesforceAddon.Build.csproj
            **/Sdl.Connectors.Tridion.SalesforceConnector.csproj
            **/Sdl.Connectors.Tridion.SalesforceDeployerConnector.csproj
          feedsToUse: 'config'
          nugetConfigPath: 'nuget.config'
          verbosityRestore: 'Minimal'

      - task: DotNetCoreCLI@2
        displayName: 'Build SalesforceConnector'
        inputs:
          command: 'build'
          projects: '**/Sdl.Connectors.Tridion.SalesforceConnector.csproj'
          arguments: '--configuration $(buildConfiguration) --no-restore'

      # Manual copy as the csproj <Copy..> does not work in the pipeline
      - task: CopyFiles@2
        displayName: 'Copy SalesforceConnector'
        inputs:
          SourceFolder: 'src/Sdl.Connectors.Tridion.SalesforceConnector/AddonPackage/SalesforceConnector'
          Contents: '**'
          TargetFolder: 'src/SalesforceAddon.Build/AddonPackage/SalesforceAddon/Connector'

      - task: DotNetCoreCLI@2
        displayName: 'Build SalesforceDeployerConnector'
        inputs:
          command: 'build'
          projects: '**/Sdl.Connectors.Tridion.SalesforceDeployerConnector.csproj'
          arguments: '--configuration $(buildConfiguration) --no-restore'

      # Manual copy as the csproj <Copy..> does not work in the pipeline
      - task: CopyFiles@2
        displayName: 'Copy SalesforceDeployerConnector'
        inputs:
          SourceFolder: 'src/Sdl.Connectors.Tridion.SalesforceDeployerConnector/AddonPackage/SalesforceDeployerConnector'
          Contents: '**'
          TargetFolder: 'src/SalesforceAddon.Build/AddonPackage/SalesforceAddon/DeployConnector'

      - task: DotNetCoreCLI@2
        displayName: 'Build Addon Package'
        inputs:
          command: 'build'
          projects: '**/SalesforceAddon.Build.csproj'
          arguments: '--configuration $(buildConfiguration) --no-restore'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Addon Package'
        inputs:
          PathtoPublish: 'src/SalesforceAddon.Build/AddonPackage'
          ArtifactName: 'SalesforceMarketingCloudAddon (Build #$(Build.BuildNumber))'
          publishLocation: 'Container'